{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "transformer.serviceAccountName" . }}
  labels:
{{ include "transformer.labels" . | nindent 4 }}
{{- end -}}
